[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cyper_v0 = "AKdZDc6qQkkUx98wjpKYhPiiLqq78tPxBrS2u3y7gG6R"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
